name: linting, testing, building 1
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  pipeline:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 19.x]
    steps:
      - uses: actions/checkout@v2
      - name: Staring Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
            node-version: ${{ matrix.node-version }}

      - name: install modules
        run: npm install

      - name: build production project
        run: npm run build:prod

      - name: linter typescript
        run: npm run lint:ts

      - name: linter css
        run: npm run lint:scss

      - name: unit testing
        run: npm run unit

      - uses: actions/checkout@v3
        with:
                 fetch-depth: 0
      - name: Publish to Chromatic
        uses: chromaui/action@v1
        with:
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}




